#!/bin/sh
# Generates Sources/RavenFeature/Generated/BakedOAuthCredentials.swift from
# Config/oauth-client.json (the same `{"installed": {"client_id": ...,
# "client_secret": ...}}` shape Google's Cloud Console downloads for a
# Desktop OAuth client), so a shipped build does not require the user to
# paste a client id/secret.
#
# Both the source JSON and the generated Swift file are gitignored — see
# .gitignore and README.md. This script is deliberately run BEFORE
# `xcodegen generate` (from the Makefile's `generate` target, not as an Xcode
# build phase): xcodegen's `sources:` list is captured as whatever files
# exist in Sources/RavenFeature at generate time, so the generated file has
# to exist before that scan, not merely before compilation.
#
# When Config/oauth-client.json is absent (a developer without the file),
# this still writes the file, with both constants `nil` — RavenRuntime falls
# back to the manual credential fields in that case, and the Accounts
# surface degrades honestly instead of shipping a Connect button that can
# never work.
set -eu

cd "$(dirname "$0")/.."

CONFIG_JSON="Config/oauth-client.json"
OUT_DIR="Sources/RavenFeature/Generated"
OUT_FILE="$OUT_DIR/BakedOAuthCredentials.swift"

mkdir -p "$OUT_DIR"

write_swift() {
    client_id_literal="$1"
    client_secret_literal="$2"
    cat > "$OUT_FILE" <<EOF
// GENERATED by scripts/generate-oauth-credentials.sh — do not edit by hand,
// and do not commit this file (see .gitignore). Regenerated by \`make generate\`
// / \`make build\` / \`make sideload\` from Config/oauth-client.json.
enum BakedOAuthCredentials {
    static let clientID: String? = $client_id_literal
    static let clientSecret: String? = $client_secret_literal
}
EOF
}

if [ ! -f "$CONFIG_JSON" ]; then
    write_swift "nil" "nil"
    echo "generate-oauth-credentials: $CONFIG_JSON not found; baking no credentials " \
         "(RavenRuntime will fall back to manually-entered credentials)." >&2
    exit 0
fi

CLIENT_ID=$(python3 -c '
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
print(data["installed"]["client_id"])
' "$CONFIG_JSON")

CLIENT_SECRET=$(python3 -c '
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
print(data["installed"]["client_secret"])
' "$CONFIG_JSON")

if [ -z "$CLIENT_ID" ] || [ -z "$CLIENT_SECRET" ]; then
    echo "generate-oauth-credentials: $CONFIG_JSON is missing client_id/client_secret" >&2
    exit 1
fi

# Swift string literal escaping: backslash and double-quote only — client ids
# and secrets from Google never contain other characters that would need it,
# but escape defensively rather than assume.
escape() {
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

write_swift "\"$(escape "$CLIENT_ID")\"" "\"$(escape "$CLIENT_SECRET")\""
echo "generate-oauth-credentials: baked credentials from $CONFIG_JSON" >&2
